Implementation of work with statistics
savushkin-r-d/ptusa-Lua-system pull request #27
Opened 2024-02-27 08:24 UTC by YaroslavOzimok

Добавлена обработка поля stat в описании устройства для работы со статистикой

2024-02-27 08:30 UTC, YaroslavOzimok commented
К запросу https://github.com/savushkin-r-d/ptusa_main/issues/597

2024-03-20 08:12 UTC, SergeiSilakov submitted a review, later dismissed

2024-03-20 08:19 UTC, AlexandrBehunkov requested changes

2024-03-20 08:19 UTC, AlexandrBehunkov commented on sys.io.lua
> +
```suggestion
```

2024-04-02 09:00 UTC, SergeiSilakov approved these changes

2025-01-23 11:37 UTC, idzm commented
Необходимо реализация данной функциональности на уровне класса `device` - чтобы соответствующие теги были сразу доступны без дополнительного описания на уровне скриптов `Lua`.

2025-01-23 11:37 UTC, closed without merging